### ISSUE TITLE
Discription text is still missing

### ISSUE THREAD

**Issue by Tom-ahawk** [kodi1/meteoalarm#6]
Installed: 5927495

The discription text is still missing(?)

![image](https://user-images.githubusercontent.com/35527507/74155122-417d2980-4c14-11ea-856e-0828d303caa7.png)

![image](https://user-images.githubusercontent.com/35527507/74155208-70939b00-4c14-11ea-9dbb-0ba1e197f2f9.png)

**Comment by kodi1** [comment]
You have a 'english' and 'norsk' languages, so you can chose between them instead of 'txt'.
'txt' is a fallback, when there are no language tags.
```
       - attr_as_list: today
          modify: x.english
          name: description
```
or
```
        - attr_as_list: today
          modify: x.norsk
          name: description
```

**Comment by Tom-ahawk** [comment]
Yes, that worked!
Thanks!
