### ISSUE TITLE
Event icon

### ISSUE THREAD

**Issue by Tom-ahawk** [kodi1/meteoalarm#7]
(Changing this issue)

In the case you want to add a icon to your integration, depending on the event, here are some icons from Material Design icon, that maybe is usable:

Wind: weather-windy
Snow/Ice: snowflake-melt
Thunderstorm: weather-lightning
Fog: weather-fog
Extreame high Temp: thermometer-plus
Extreame low temp: thermometer-minus
Costal evenet: island
Forest fire: pine-tree
Avalances: snowflake-variant
Rain: weather-rainy
Flood: waves
Rain-Flood: weather-pouring

**Comment by kodi1** [comment]
Feel free to submit PR .

**Comment by Tom-ahawk** [comment]
PR, - I would if I could, total N00b here. 

But looking at your sensor code, def icon(self), have a case statement adding the icon depening on the event(?)
